In [1]:
import numpy as np;
import pandas as pd;

In [5]:
arr1 = np.arange(0,10)
np.all(arr1)

False

In [6]:
#Write a NumPy program to test whether none of the elements of a given array are zero.
arr1 = np.array([1,2,4,5])
np.all(arr1)

True

In [9]:
#Write a NumPy program to test if any of the elements of a given array are non-zero. 

In [8]:
np.any(arr1)

True

In [21]:
#Write a NumPy program to test element-wise for NaN of a given array.

In [22]:
arr2 = np.array([np.nan,45,5,6,np.nan])
np.isnan(arr2)

array([ True, False, False, False,  True])

In [26]:
#Write a NumPy program to test a given array element-wise for finiteness
arr3 = np.array([1,2,np.nan,np.inf,-np.inf])


In [29]:
np.isfinite(arr3)

array([ True,  True, False, False, False])

In [28]:
#Write a NumPy program to test elements-wise for positive or negative infinity.
np.isinf(arr3)

array([False, False, False,  True,  True])

In [32]:
#Write a NumPy program to test element-wise for complex numbers, real numbers in a given array.
#Also test if a given number is of a scalar type or not.
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))
print(np.isscalar(a))
print(np.isscalar('abcd'))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False
False
True


In [34]:
#Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [35]:
#Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [42]:
arr7 = np.array([3,4,6,5])
arr8 = np.array([4,2,9,5])
np.greater(arr7,arr8)
np.greater_equal(arr7,arr8)
np.less_equal(arr7,arr8)
np.less(arr7,arr8)

array([ True, False,  True, False])